name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Show info
      run: |
        whoami
        pwd
        type python3
        type pip3
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y git bzip2 autoconf unzip
        sudo apt-get install -y python3-full python3-dev
    - name: Show python venv
      run: |
        pip3 install Sphinx myst-parser linkify-it-py
        python3 -c "import sys; print(sys.version)"
        python3 -c "import sys; print(sys.path)"
    - name: Build qlat-docs
      run: |
        make html
        [ -f $PWD/build/html/index.html ]
    - uses: actions/upload-artifact@v4
      with:
        name: html
        path: build/html
    - uses: actions/configure-pages@v4
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build/html

  deploy_docs:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
